#ifndef REPLIES_HPP
# define REPLIES_HPP

enum ReplyCode {
    ERR_NEEDMOREPARAMS = 461,
    ERR_NOSUCHCHANNEL  = 403,
    ERR_BADCHANMASK    = 476,
    ERR_NICKNAMEINUSE  = 433,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_USERONCHANNEL  = 443,
    ERR_BADCHANNELKEY  = 475,
    ERR_CHANNELISFULL  = 471,
    ERR_INVITEONLYCHAN = 473,
    ERR_NOTONCHANNEL   = 442,
    ERR_CHANOPRIVSNEEDED = 482,
    RPL_NOTOPIC        = 331,
    RPL_TOPIC          = 332,
    RPL_YOUREOPER      = 705
};

#endif